services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: portal_lux_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: